dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - travis_retry pip install pipenv
  - travis_retry pipenv install coverage coveralls -e . --dev

script: py.test --cov pyjolt --cov-report term-missing --flakes

after_script:
  - coveralls

branches:
  only:
    - master
