language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - travis_retry pip install pipenv
  - travis_retry pipenv install coverage coveralls
  - travis_retry pipenv install -e .

script: py.test --cov pyjolt --cov-report term-missing --flakes

after_script:
  - coveralls

branches:
  only:
    - master
